config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :listing_attachments

  resources :listings

  get 'page/index'

  get 'page/investments'

  get 'page/portfolio'

  get 'page/services'

  get 'page/contact'

  root 'page#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  has_many :listing_attachments
  accepts_nested_attributes_for :listing_attachments
end

app/models/listing_attachment.rb
class ListingAttachment < ActiveRecord::Base
  mount_uploader :listing_image, ListingImagesUploader
  belongs_to :listing, foreign_key: "listing_id"
end

app/models/role.rb
class Role < ActiveRecord::Base
   has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create :set_default_role

  private
   def set_default_role
     self.role ||= Role.find_by_name('registered')
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listing_attachments_controller.rb
class ListingAttachmentsController < ApplicationController
  before_action :set_listing_attachment, only: [:show, :edit, :update, :destroy]

  # GET /listing_attachments
  # GET /listing_attachments.json
  def index
    @listing_attachments = ListingAttachment.all
  end

  # GET /listing_attachments/1
  # GET /listing_attachments/1.json
  def show
  end

  # GET /listing_attachments/new
  def new
    @listing_attachment = ListingAttachment.new
  end

  # GET /listing_attachments/1/edit
  def edit
  end

  # POST /listing_attachments
  # POST /listing_attachments.json
  def create
    @listing_attachment = ListingAttachment.new(listing_attachment_params)

    respond_to do |format|
      if @listing_attachment.save
        format.html { redirect_to @listing_attachment, notice: 'Listing attachment was successfully created.' }
        format.json { render :show, status: :created, location: @listing_attachment }
      else
        format.html { render :new }
        format.json { render json: @listing_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listing_attachments/1
  # PATCH/PUT /listing_attachments/1.json
  def update
    respond_to do |format|
      if @listing_attachment.update(listing_attachment_params)
        format.html { redirect_to @listing_attachment, notice: 'Listing attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing_attachment }
      else
        format.html { render :edit }
        format.json { render json: @listing_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listing_attachments/1
  # DELETE /listing_attachments/1.json
  def destroy
    listing_id = @listing_attachment.id
    @listing_attachment.destroy
    respond_to do |format|
      format.html { redirect_to listing_attachments_url, notice: 'Listing attachment was successfully destroyed.' }
      format.json { render json: {status: "ok", id: listing_id} }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing_attachment
      @listing_attachment = ListingAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_attachment_params
      params.require(:listing_attachment).permit(:listing_id)
    end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  include SessionHelper
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :check_if_admin, only: [:create, :edit, :update, :destroy, :new, :index]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @listing_attachments = @listing.listing_attachments.all
  end

  # GET /listings/new
  def new
    @listing = Listing.new
    @listing_attachment = @listing.listing_attachments.build
  end

  # GET /listings/1/edit
  def edit
  end

  # GET /listings/1/edit_attachments
  def edit_attachments
    @listing = Listing.find(params[:id])
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        params[:listing_attachments]['listing_attachment'].each do |l|
           @listing_attachment = @listing.listing_attachments.create!(:listing_image => l, :listing_id => @listing.id)
        end
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        params[:listing_attachments]['listing_attachment'].each do |l|
           @listing_attachment = @listing.listing_attachments.create!(:listing_image => l, :listing_id => @listing.id)
        end
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def check_if_admin
      if(is_admin?)
        return true
      else
        flash[:notice] = 'You need to be signed in to perform that action'
        redirect_to :back
      end
    end

    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:title, :description, listing_attachments_attributes: [:id, :listing_id, :listing_image])
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  layout "pages"
  def index
    @name = "home"
  end

  def investments
    @name = "investments"
  end

  def portfolio
    @name = "portfolio"
  end

  def contact
    @name = "contact"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionHelper
  before_filter :authenticate_user!
  before_action :check_if_admin

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

  private
    def check_if_admin
      if(is_admin?)
        return true
      else
        flash[:notice] = 'You need to be signed in to perform that action'
        redirect_to :back
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def getListings
    listings = Listing.all
  end

end

app/helpers/listing_attachments_helper.rb
module ListingAttachmentsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/session_helper.rb
module SessionHelper

  def is_admin?
    if(user_signed_in?)
      if(current_user.role.name == "admin")
        return true
      end
    end

    return false
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prudentialinvestments</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "shared/header" %>

<%= yield %>

<%= render "shared/footer" %>

</body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prudential Investments</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "shared/header" %>

<%= yield %>

<%= render "shared/footer" %>

</body>
</html>

app/views/listing_attachments/_form.html.erb
<%= form_for(@listing_attachment) do |f| %>
  <% if @listing_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing_attachment.errors.count, "error") %> prohibited this listing_attachment from being saved:</h2>

      <ul>
      <% @listing_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :listing_id %><br>
    <%= f.number_field :listing_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listing_attachments/edit.html.erb
<h1>Editing listing_attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing_attachment %> |
<%= link_to 'Back', listing_attachments_path %>

app/views/listing_attachments/index.html.erb
<h1>Listing listing_attachments</h1>

<table>
  <thead>
    <tr>
      <th>Listing</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listing_attachments.each do |listing_attachment| %>
      <tr>
        <td><%= listing_attachment.listing_id %></td>
        <td><%= link_to 'Show', listing_attachment %></td>
        <td><%= link_to 'Edit', edit_listing_attachment_path(listing_attachment) %></td>
        <td><%= link_to 'Destroy', listing_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing attachment', new_listing_attachment_path %>

app/views/listing_attachments/new.html.erb
<h1>New listing_attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', listing_attachments_path %>

app/views/listing_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Listing:</strong>
  <%= @listing_attachment.listing_id %>
</p>

<%= link_to 'Edit', edit_listing_attachment_path(@listing_attachment) %> |
<%= link_to 'Back', listing_attachments_path %>

app/views/listings/_form.html.erb
<%= form_for(@listing, :html => { :multipart => true }) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <br>
  <div class="row images-row">
    <% @listing.listing_attachments.each do |att| %>
      <div class="col-lg-3" id="attachment_<%= att.id %>">
          <img src="<%= att.listing_image.url %>" alt="" />
          <div class="actions">
            <a href="/listing_attachments/<%= att.id %>.json" class="delete_attachment">
              <span class="glyphicon glyphicon-trash"></span>
            </a>
          </div>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :listing_attachments %><br>
    <%= f.file_field :listing_attachments, :multiple => true, name: "listing_attachments[listing_attachment][]" , class: "form-control"%>
  </div>

  <br />

  
  <div class="actions">
    <%= f.submit class: "btn"%>
  </div>

  <br>
<% end %>

app/views/listings/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1>Editing listing</h1>

      <%= render 'form' %>

      <%= link_to 'Show', @listing %> |
      <%= link_to 'Back', listings_path %>
    </div>
  </div>
</div>

app/views/listings/edit_attachments.html.erb
<div class="container">
  <div class="row">
    <% @listing.listing_attachments.each do |att| %>
      <div class="col-lg-3">
          <img src="<%= att.listing_image.url %>" alt="" />
          <div class="actions">
            <span class="glyphicon glyphicon-trash"></span>
          </div>
      </div>
    <% end %>
    <form class="" action="index.html" method="post">
      <input type="file" name="name" value="">
      <input type="submit" name="name" value="">
    </form>
  </div>
</div>

app/views/listings/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>Listing listings</h1>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @listings.each do |listing| %>
            <tr>
              <td><%= listing.title %></td>
              <td><%= listing.description %></td>
              <td><%= link_to 'Show', listing %></td>
              <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
              <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Listing', new_listing_path %>
    </div>
  </div>
</div>

app/views/listings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>New listing</h1>

      <%= render 'form' %>

      <%= link_to 'Back', listings_path %>
    </div>
  </div>
</div>

app/views/listings/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div id="carousel-property" class="carousel slide carousel-listing" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <% @listing_attachments.each_with_index do |item, i| %>
          <% if(i == 0)%>
              <li data-target="#carousel-property" data-slide-to="<%= i %>" class="active"></li>
          <% else %>
              <li data-target="#carousel-property" data-slide-to="<%= i %>"></li>
          <% end %>
        <% end %>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <% @listing_attachments.each_with_index do |item, i| %>
          <% if(i == 0)%>
            <div class="item active" style="background-image:url(<%= item.listing_image.url %>)">
          <% else %>
            <div class="item" style="background-image:url(<%= item.listing_image.url %>)">
          <% end %>

          </div>
        <% end %>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-property" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-property" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
<div>


<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <p id="notice"><%= notice %></p>

      <h1><%= @listing.title %></h1>

      <p>
        <%= @listing.description %>
      </p>

      <% if(is_admin?) %>
        <%= link_to 'Edit', edit_listing_path(@listing) %> |
        <%= link_to 'Back', listings_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/page/.#portfolio.html.erb
nacho@raiden.3428:1407304270

app/views/page/about.html.erb
    <div id="carousel-homepage" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
	<li data-target="#carousel-homepage" data-slide-to="0" class="active"></li>
	<li data-target="#carousel-homepage" data-slide-to="1"></li>
	<li data-target="#carousel-homepage" data-slide-to="2"></li>
      </ol>
            
      <!-- Wrapper for slides -->
      <div class="carousel-inner">
	<div class="item active">
	  <img src="/assets/header-about.jpg" alt="Los Angeles">
	  <div class="carousel-caption">
	    <h1>We worry about what is best</h1>
	    Ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditatea est.
	  </div>
	</div>
	<div class="item">
	  <img src="/assets/header1.jpg" alt="Los Angeles">
	  <div class="carousel-caption">
	    <h2>A city to be discovered</h2>
	  </div>
	</div>
	<div class="item">
	  <img src="/assets/header1.jpg" alt="Los Angeles">
	  <div class="carousel-caption">
	    <h2>Beyond what is good</h2>
	  </div>
	</div>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-homepage" data-slide="prev">
	<span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#carousel-homepage" data-slide="next">
	<span class="glyphicon glyphicon-chevron-right"></span>
      </a>
      <div class="overlay"></div>
    </div>
<div class="container">
  <div class="row">
    <div class="col-md-12" style="text-align:center">
      <h1>We communicate the best deals available</h1>
      <div>
	Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum q
      </div>
    </div>
  </div>
  <div class="row about-icons">
    <div  class="col-md-4">
      <span class="glyphicon glyphicon-th-list"></span>
    </div>
    <div  class="col-md-4">
      <span class="glyphicon glyphicon-map-marker"></span>
    </div>
    <div  class="col-md-4">
      <span class="glyphicon glyphicon-send"></span>
    </div>
  </div>
  <div class="row team-images">
    <div  class="col-md-4">
      	Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim
    </div>
    <div  class="col-md-4">
      	Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim
    </div>
    <div  class="col-md-4">
      	Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim
    </div>
  </div>
    
</div>

app/views/page/contact.html.erb
<div id="carousel-homepage" class="carousel-homepage carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-homepage" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-homepage" data-slide-to="1"></li>
    <li data-target="#carousel-homepage" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active" style="background-image:url(/assets/header-services.jpg)">
      <div class="carousel-caption">
        <h1>Get in touch with us</h1>
        Ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditatea est.
      </div>
    </div>
    <div class="item" style="background-image:url(/assets/header-about.jpg)">
      <div class="carousel-caption">
        <h1>We worry about what is best</h1>
        Ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditatea est.
      </div>
    </div>
    <div class="item" style="background-image:url(/assets/header1.jpg)">
      <div class="carousel-caption">
        <h2>Beyond what is good</h2>
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-homepage" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-homepage" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
  
  <div class="overlay"></div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>Contact Us</h1>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
      <form class="" action="index.html" method="post">
        <input type="text" name="name" class="form-control" value="" placeholder="Name" />
        <br>
        <input type="text" name="name" class="form-control" value="" placeholder="Email" />
        <br>
        <textarea name="name" class="form-control" rows="8" cols="40" placeholder="Your Message"></textarea>
        <br>
        <input type="submit" class="btn btn-default" name="name" value="Submit">
      </form>
    </div>
  </div>
</div>

app/views/page/index.html.erb
<% if notice %>
  <div class="alert-container">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="alert alert-danger" role="alert"><%= notice %></div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div id="carousel-homepage" class="carousel-homepage carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
  	<li data-target="#carousel-homepage" data-slide-to="0" class="active"></li>
  	<li data-target="#carousel-homepage" data-slide-to="1"></li>
  	<li data-target="#carousel-homepage" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
  	<div class="item active" style="background-image:url(assets/header1.jpg);">
  	  <div class="carousel-caption">
  	    <h1>Welcome to Prudential Capital Management</h1>
  	  </div>
  	</div>
  	<div class="item" style="background-image:url(assets/header-about.jpg);">
  	  <div class="carousel-caption">
  	    <h2>A city to be discovered</h2>
  	  </div>
  	</div>
  	<div class="item" style="background-image:url(assets/header-services.jpg);">
  	  <div class="carousel-caption">
  	    <h2>Unique Real Estate investment opportunities</h2>
  	  </div>
  	</div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-homepage" data-slide="prev">
     <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-homepage" data-slide="next">
     <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
  <div class="overlay"></div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Sign  up for our Hot Property report</h1>
    </div>
  </div>
  <div class="row page-section">
    <div class="col-md-8">
     <h4 class="justified"> You're investing in debt, not equity, so in a market that moves at top speed, it is important to be updated when a hot deal comes up before it's snatched. Sign up with us to recieve notifications only when it matters. You can start participating as an accredited investor and fund projects with confidence in the hard asset of property.</h4>
    </div>
    <div class="col-md-4 button-container">
      <!-- div type="button" class="btn-lg btn-success" data-toggle="modal" data-target="#myModal">Sign Up</div -->
      <a href="/users/sign_up" class="btn btn-success">Sign Up (free)</a>
    </div>
  </div>

  <hr class="featurette-divider" style="border-color:#CCCCCC; margin-top:50px; margin-bottom:50px;" />

  <div class="row team-images">
    <div  class="col-md-6">
      <img class="img-circle" data-src="holder.js/140x140" alt="140x140" src="/assets/house-circle1.jpg" style="width: 200px; height: 200px;" />
    </div>
    <div  class="col-md-6">
      <img class="img-circle" data-src="holder.js/140x140" alt="140x140" src="/assets/house-circle2.jpg" style="width: 200px; height: 200px;">
    </div>
  </div>

  <div class="row team-description">
    <div  class="col-md-6 justified">
    High-end design meets one of Laguna Niguel’s most vibrant and culturally rich neighborhoods in this deluxe and modern family home that spans three levels beginning with its own private entry on the ground level and a roof deck that looks out over the beach and beyond.
124 Crestview is one of only five exclusive homes that were built as part of the highly desirable 300 Crestview project in 2013. Designed by renowned architecture firm, D&B, it features thoughtful design with a balance of substance and style. This incredibly special home stands out from the rest! It has been upgraded with designer touches throughout.

    </div>
    <div  class="col-md-6 justified">
      Enchanting, private, serene, hip, sophisticated… Located in the ultimate urban location, this light-filled two bedroom Victorian home features a separate and legal apartment down that is open, tranquil and walks out to a zen-like garden. This unique property affords many options: Owner’s home with in-law unit or private suite, 2 TIC’s with fast track condo conversion, or owner’s home with lower rental unit.
    </div>
  </div>

  <hr class="featurette-divider" style="border-color:#CCCCCC; margin-top:50px; margin-bottom:50px;" />

  <div class="row featurette">
        <div class="col-md-6" style="text-align:center;">
          <img class="img-responsive" style="display:inline-block;border-radius:5px;overflow:hidden; border:1px solid #cccccc; padding:2px" data-src="holder.js/350x350/auto" alt="House" src="/assets/house1.jpg">
        </div>
        <div class="col-md-6">
          <h2 class="featurette-heading">Yes, it's that easy. <span class="text-muted">See for yourself.</span></h2>
          <p class="lead justified">
	    Unique real estate investments often require unique financing solutions. specific transactions might require higher loan-to-value, mezzanine finance, equity, or any combination thereof. <br/>Through our directly managed fund and relationships in the capital markets, Prudential Capital Management can design a capital stack tailored for any real estate investment.
	  </p>
        </div>
  </div>
</div>

app/views/users/_user.html.erb
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h3>Users</h3>
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>